#alpine is a lightweight linux distribution
FROM alpine:3.19
# apk add --no-cache curl git bash jq installs the following packages
# curl - Transfer a URL
# git - The distributed version control system
# bash - GNU Bash Shell
# jq - A lightweight and flexible command-line JSON processor 
RUN apk add --no-cache curl git bash jq
# Set the working directory to /workspace
WORKDIR /workspace
