name: Build and push base image

on: 
  push:
    branches:
      - dev
      - test
      - stage
    # paths:
    #   - 'base-image/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/Checkout@v5
    