name: Build and push docker dind image

on: 
  push:
    branches:
      - dev
      - test
      - stage
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v5
      