name: Build and push gpu-ml image

on: 
  push:
    branches:
      - dev
      - test
      - stage
    paths:
      - 'images/runner-gpu-ml/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v5
      