name: Build job container for Android SDK

on: 
  push:
    branches:
      - dev
      - stage
    paths:
      - "jobcontainers/build-android-sdk/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push job container image
        uses: docker/build-push-action@v5
        with:
          context: ./jobcontainers/build-android-sdk
          push: true
          tags:
            ${{ vars.registry }}/mailtovignesh/build-android-sdk:${{ github.run_number }}
  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v3
        with:
          image: ${{ vars.registry }}/mailtovignesh/build-android-sdk:${{ github.run_number }}
          format: 'table'
          exit-code: '1'
  push:
    runs-on: ubuntu=latest
    needs: [build, scan]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push Image
        run: docker push ${{ vars.registry }}/mailtovignesh/build-android-sdk:${{ github.run_number }}