name: Build and push python image

on: 
  push:
    branches:
      - dev
      - test
      - stage
    paths:
      - 'images/runner-python/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v5
      